### PR TITLE
Statement coverage increased to 100%

### PR DESCRIPTION
**Pull request by ntnl**
Hi!

I'm taking part of the CPAN pull request challenge.
This PR should increase statement coverage to 100%

Regards.

### CODE REVIEW

**Comment by kberov** [comment]
Hey, @ntnl , Thanks! Let me see! :+1:

**Comment by kberov** [comment]
Thanks!

**Comment by ntnl** [comment]
```
 Hi!
```

> It is not 100% at least how I, measure it but for sure it should be 
> better :).
> 
> The coverage was a starting point, the actual target was to verify if - 
> and how - exceptions are handled.

As a side note, I found out that if you load all plugins from given 
namespace, you will not get an exception if some of them do not load.
I do not know if that is significant, as I'm not a big Mojo user.

> |$ cover
> Reading database from /home/berov/opt/public_dev/Mojolicious--Plugin--DSC/cover_db
> 
> ---
> 
> File                           stmt   bran   cond    sub    pod   time  total
> 
> ---
> 
> ...Mojolicious/Plugin/DSC.pm   96.5   65.3   80.6  100.0  100.0  100.0   84.7
> Total                          96.5   65.3   80.6  100.0  100.0  100.0   84.7
> 
> ---
> 
> |
> |
> 
> How do you measure?
> 
> rm -rf cover_db/ && PERL5OPT=-MDevel::Cover prove -r t/ && cover -report 
> html
> 
> Thanks!
> 
> Your welcome :)

I'm happy to see that the contribution proved useful.

## 

_Bartłomiej Syguła_

**Comment by kberov** [comment]
Hi Bartłomiej,
It was my mistake.  I ran it later using simply `cover -test`. It showed 100% I added some more tests.
Now the situation is as follows:

```
---------------------------- ------ ------ ------ ------ ------ ------ ------
File                           stmt   bran   cond    sub    pod   time  total
---------------------------- ------ ------ ------ ------ ------ ------ ------
...Mojolicious/Plugin/DSC.pm  100.0   80.0   85.1  100.0  100.0  100.0   91.7
Total                         100.0   80.0   85.1  100.0  100.0  100.0   91.7
---------------------------- ------ ------ ------ ------ ------ ------ ------

```

I uploaded a new version to CPAN. Also mantioned you in Changes. See 1.003 2015-02-28
https://metacpan.org/changes/distribution/Mojolicious-Plugin-DSC
Thanks again.

**Comment by ntnl** [comment]
W dniu 02.03.2015 o 15:20, Красимир Беров pisze:

> Hi Bartłomiej,
> It was my mistake. I ran it later using simply |cover -test|. It 
> showed 100% I added some more tests.
> Now the situation is as follows:
> 
> |---------------------------- ------ ------ ------ ------ ------ ------ ------
> File                           stmt   bran   cond    sub    pod   time  total
> 
> ---
> 
> ...Mojolicious/Plugin/DSC.pm  100.0   80.0   85.1  100.0  100.0  100.0   91.7
> Total                         100.0   80.0   85.1  100.0  100.0  100.0   91.7
> ---------------------------- ------ ------ ------ ------ ------ ------ ------|
> |
> Cool, looks good!|

## 

_Bartłomiej Syguła_

**Pull request merged**
